Change Prep init to pass folders as parameter
PaddleCV-SIG/MedicalSeg pull request #32
Opened 2022-02-28 13:21 UTC by linhandev

Pass folders to Prep with init parameters, this way the prep class couples less with subclass

2022-03-07 13:15 UTC, shiyutang requested changes

2022-03-07 13:15 UTC, shiyutang commented on tools/prepare.py
> +        visualize_fdr="vis",
visualize file can be stored in each experiment path

2022-03-07 13:15 UTC, shiyutang commented on tools/prepare.py
> +        label_fdr,
These attributes can have default params.

2022-03-08 03:29 UTC, linhandev commented on tools/prepare.py
> +        label_fdr,
This directory varies from dataset to dataset. 

These two params will be used in `self.image_dir`, this path is the raw path for the dataset / image folder in zip. Like for msd task 1 `self.image_fdr` is Task01_BrainTumour/Task01_BrainTumour/imagesTr

2022-03-08 03:34 UTC, linhandev commented on tools/prepare.py
> +        visualize_fdr="vis",
Roger.

I planed to store visualization for preprocessed data here but it isnt really used.

Will look into visualization more thoroughly this week. Maybe we can just merge it like this for now. I can fix this in a future pr. This way I won't need to change all the latter prs.

2022-03-09 01:54 UTC, shiyutang commented on tools/prepare.py
> +        label_fdr,
I see

2022-03-09 01:55 UTC, shiyutang commented on tools/prepare.py
> +        visualize_fdr="vis",
ok

2022-03-09 02:02 UTC, shiyutang reviewed
You may want to run the prepare_lung_coronavirus.py to see if the result directory is as follows. Just in case something went wrong.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/34859558/157357830-0d8d7907-cd9f-4327-89f7-2c20b0938070.png">

2022-03-23 06:36 UTC, shiyutang commented
The content in this PR have been incorporate into the current code

2022-03-23 06:36 UTC, closed without merging