Fix some typos in README
PaddleCV-SIG/MedicalSeg pull request #40
Opened 2022-03-06 07:46 UTC by linhandev

2022-03-06 07:46 UTC, linhandev commented on README.md
> +    git clone https://github.com/PaddleCV-SIG/MedicalSeg/
repo地址貌似没改

2022-03-06 07:47 UTC, linhandev commented on README.md
> +    python tools/prepare_lung_coronavirus.py
前面是在 MedicalSeg 目录下，跑prep脚本应该需要前面加上 tools

2022-03-07 12:11 UTC, shiyutang requested changes

2022-03-07 12:11 UTC, shiyutang commented on README.md
> +    git clone https://github.com/PaddleCV-SIG/MedicalSeg/
The repo address is https://github.com/PaddleCV-SIG/MedicalSeg.git

2022-03-09 01:45 UTC, shiyutang approved these changes

2022-03-09 01:45 UTC, merged