[Feature] Add MRISpineSeg dataset
PaddleCV-SIG/MedicalSeg pull request #41
Opened 2022-03-07 12:08 UTC by shiyutang

2022-03-17 07:47 UTC, shiyutang reviewed
Finished self-checking

2022-03-18 02:39 UTC, parap1uie-s requested changes

2022-03-18 02:39 UTC, parap1uie-s commented on medicalseg/core/val.py
> +                        'pred': pred.clone().detach().numpy(),
没必要吧，直接numpy()？

2022-03-18 03:16 UTC, shiyutang commented on medicalseg/core/val.py
> +                        'pred': pred.clone().detach().numpy(),
done

2022-03-18 03:16 UTC, merged