[Feature] Add decathlon format convert code
PaddleCV-SIG/MedicalSeg pull request #49
Opened 2022-03-28 12:28 UTC by justld

添加数据集预处理代码（移除.* 文件、4d切分3d），转换为decathlon格式。
示例：
```python
from preprocess_utils import verify_dataset_integrity
convert_to_decathlon(input_folder=“\xxx\Task06_Lung”, 
                output_folder='\xxx\Task006_Lung', 
                data_json="dataset.json", 
                train_images_dir="imagesTr", 
                train_labels_dir="labelsTr", 
                test_images_dir="imagesTs", 
                num_processes=8)
```

2022-03-29 04:28 UTC, linhandev commented on paddleseg3d/datasets/preprocess_utils/convert_to_decathlon.py
> +def split_4d_to_3d_and_save(img_itk: sitk.Image, output_folder,
这种读再写的方式会不会比较慢

2022-03-30 11:36 UTC, shiyutang requested changes

2022-03-30 11:36 UTC, shiyutang commented on paddleseg3d/datasets/preprocess_utils/convert_to_decathlon.py
> +def split_4d_to_3d_and_save(img_itk: sitk.Image, output_folder,
这部分，可以尝试直接调用这个PR中代码：https://github.com/PaddleCV-SIG/MedicalSeg/pull/52/files#diff-3d018619025bdd5b7ced847afd997c3f4ec9b122044522f0307e99a2e6709fab

2022-03-31 08:24 UTC, justld commented on paddleseg3d/datasets/preprocess_utils/convert_to_decathlon.py
> +def split_4d_to_3d_and_save(img_itk: sitk.Image, output_folder,
感谢建议，已修改。

2022-03-31 08:25 UTC, justld commented on paddleseg3d/datasets/preprocess_utils/convert_to_decathlon.py
> +def split_4d_to_3d_and_save(img_itk: sitk.Image, output_folder,
感谢建议，已修改。

2022-04-06 03:46 UTC, shiyutang requested changes
需要解决冲突之后提交到nnunet分支

2022-04-06 03:47 UTC, justld commented
已修改

2022-04-06 06:07 UTC, shiyutang approved these changes
LGTM

2022-04-06 06:07 UTC, merged