[Feature] Add 3D msd dataset support
PaddleCV-SIG/MedicalSeg pull request #50
Opened 2022-03-29 03:02 UTC by linhandev

2022-03-29 03:04 UTC, linhandev commented on tools/prepare.py
> -                 images_dir="train_imgs", labels_dir="train_labels", phase_dir="phase0",
我用的这个atom貌似默认会删这种行尾空格，研究了半天也没弄明白在哪关这个。我基本上没format代码，如果有这种纯格式修改会单独出来一个commit

2022-03-29 03:04 UTC, linhandev commented on tools/prepare.py
> -                 images_dir="train_imgs", labels_dir="train_labels", phase_dir="phase0",
这种应该不是很多

2022-03-29 03:56 UTC, linhandev commented on .gitignore
> +data/
在git记录里忽略数据路径

2022-03-29 04:23 UTC, linhandev commented on tools/prepare.py
> +        if osp.exists(self.raw_data_path):
self.raw_data_path 存在时跳过解压

2022-03-29 04:24 UTC, linhandev commented on tools/prepare.py
> +            f_np = np.transpose(f_np, [2,1,0])
msd的数据集读进来是需要transpose的

2022-03-29 04:24 UTC, linhandev commented on tools/prepare.py
> +                img_itk = sitk.ReadImage(image_name)
少读一次，速度快1/3左右

2022-03-29 04:26 UTC, linhandev commented on tools/preprocess_utils/dataset_json.py
> +import json
msd数据集本来就是有json的，这个函数读msd的json，按照 prep.generate_dataset_json 的格式返一个dict，方便从旧的dataset.json创建新的

2022-03-29 04:26 UTC, linhandev commented on tools/preprocess_utils/uncompress.py
> +        elif filepath.endswith(("tgz", "tar", "tar.gz")):
这貌似应该传tuple，原来的写法报错

2022-03-29 04:34 UTC, linhandev commented on tools/preprocess_utils/dataset_json.py
> +def parse_msd_basic_info(json_path):
msd数据集本来就是有json的，这个函数读msd的json，按照 prep.generate_dataset_json 的格式返一个dict，方便从旧的dataset.json创建新的

2022-03-29 09:58 UTC, shiyutang requested changes

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare.py
> -                 images_dir="train_imgs", labels_dir="train_labels", phase_dir="phase0",
没关系

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare.py
> +            f_np = np.transpose(f_np, [2,1,0])
可以在load_medical_data中加一个format的参数，默认是“zyx”（对msd的数据集传入是“xyz”）；然后在load的if判断外面，增加对format的判断，如果不是“zyx”，就对输入进行相应的transpose。

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare.py
> +        tic = time.time()
这里就只改了“tic”么，看上去改了三行

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare_msd.py
> +            name.replace("_org_covid-19-pneumonia-",
这里是否相应需要修改，根据npy 的 image来对应找到npy 的 label

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare_msd.py
> +                        "labels":[wrapped_partial(resample, new_shape=[128, 128, 128], order=0),]}
关于预处理的话，最好能根据不同数据集进行预处理尺寸的变化；HUNorm对于不同数据，也是有不同参数的。

2022-03-29 09:58 UTC, shiyutang commented on tools/prepare_msd.py
> +                        "labels":[wrapped_partial(resample, new_shape=[128, 128, 128], order=0),]}
如果这里数据集太多，可以先针对肺部数据集进行对应参数的修改。
或者，我们可以类似nnunet，增加一下根据不同数据集，生成相应参数的方法，自动化参数设置的内容。

2022-03-29 21:43 UTC, linhandev commented on tools/prepare.py
> +            f_np = np.transpose(f_np, [2,1,0])
感觉这个可能可以用头文件里的信息判断，nib和sitk比感觉功能弱一些，准备用sitk做这块

2022-03-29 21:45 UTC, linhandev commented on tools/prepare.py
> +        tic = time.time()
这两行内容完全一样，感觉好像是类似行尾空格的问题。执行过程中也没看到什么异常

2022-03-29 22:09 UTC, linhandev commented on tools/prepare_msd.py
> +                        "labels":[wrapped_partial(resample, new_shape=[128, 128, 128], order=0),]}
感觉这个预处理参数可能跟预处理的use_gpu一样写到一个yaml里更合适。这个prep_msd不像另两个prep是只针对一个数据集的，msd感觉更类似coco这种是种比较通用的格式，在这个格式下msd比赛有10个，nnunet那边在10个之外还有一些，未来用户从nnunet过来的话可能也可以用这个脚本预处理原来用来给nnunet训练的数据。

我们可能可以这一版先固定这几个参数，先把msd的4d导入，体味矫正什么的这种周边的小点清了，之后先加入yaml配置，内置10数据集nnunet生成的超参方便对齐，之后做一个生成超参的流程

2022-03-29 22:13 UTC, linhandev commented on tools/prepare_msd.py
> +            name.replace("_org_covid-19-pneumonia-",
恩恩是的，这没注意到，已经修改。msd的图像和标签名字一样，这个replace其实没起作用

2022-03-30 10:12 UTC, shiyutang requested changes

2022-03-30 10:12 UTC, shiyutang commented on tools/prepare.py
> +            f_np = np.transpose(f_np, [2,1,0])
嗯嗯，但是这个要先改好，因为当前的写法和之前的数据是不兼容的

2022-03-30 10:12 UTC, shiyutang commented on tools/prepare_msd.py
> +                        "labels":[wrapped_partial(resample, new_shape=[128, 128, 128], order=0),]}
好的

2022-03-30 13:03 UTC, linhandev commented on tools/prepare.py
> +            f_np = np.transpose(f_np, [2,1,0])
pr 52解决了这个问题，我把52的那个commitpick到这个branch来

2022-03-31 01:09 UTC, shiyutang commented
> 添加3D msd数据集的预处理。在msd task 2 3 6 7 8 9 10上进行了测试
> 
> 示例：
> 
> ```shell
> python tools/prepare_msd.py 4 
> ```

对于1, 4, 5 有测试吗

2022-03-31 01:14 UTC, shiyutang requested changes

2022-03-31 01:14 UTC, shiyutang commented on tools/prepare.py
>          else:
mhd 和 raw 也需要支持

2022-04-01 20:44 UTC, linhandev commented on tools/prepare.py
>          else:
这个格式的数据集我貌似没有，我记得3d ircadb貌似是，找来试试

2022-04-01 20:45 UTC, linhandev commented
> 
今天加完mhd格式整个测一下

2022-04-05 01:10 UTC, linhandev commented
> > 添加3D msd数据集的预处理。在msd task 2 3 6 7 8 9 10上进行了测试
> > 示例：
> > ```shell
> > python tools/prepare_msd.py 4 
> > ```
> 
> 对于1, 4, 5 有测试吗

上述3d都测过，刚测了task 1的4d修了一个小问题。正在重新全跑一遍，但是感觉需要很长时间。准备更新wrapop之后上多进程加一下速

2022-04-05 01:54 UTC, linhandev commented on tools/prepare.py
>          else:
3d ircadb是dcm格式，这个数据集还得再找找，但是mhd格式的处理和之前基本没有区别

2022-04-05 07:07 UTC, linhandev reviewed
感觉功能上大概差不多了

2022-04-05 07:07 UTC, linhandev commented on tools/prepare.py
>          else:
nrrd的数据集没找到，我用itksnap把一个nii转成了nrrd单独测试修改了这一块

2022-04-05 07:08 UTC, linhandev commented on tools/prepare.py
>          else:
nrrd的数据集没找到，我用itksnap把一个nii转成了nrrd单独测试修改了这一块

2022-04-06 08:39 UTC, shiyutang reviewed
4D拆分需要确定是否独立处理

2022-04-06 08:39 UTC, shiyutang commented on tools/prepare.py
> +            f_nps = [np.swapaxes(f_np, 0, 2) for f_np in f_nps] # swap to xyz
对于所有数据集都需要进行转换到xyz吗，这里需要仔细检查一下，包括之前的lung_coronavirus 和mri_spine_seg

2022-04-06 08:39 UTC, shiyutang commented on tools/prepare.py
> +                        dataset_json_dict["training"][osp.basename(f).split(".")[0]]["spacing_resample"] = new_spacing
这边是针对每个file只有个spacing 不需要缩进，如果4D每维度的 file 都是不同的spacing需要考虑先做拆分存储，形成dataset.json，然后再load_save。比如使用这个PR中的 convert_decathlon: https://github.com/PaddleCV-SIG/MedicalSeg/pull/49

2022-04-06 08:40 UTC, shiyutang commented on tools/prepare.py
>          else:
mhd的可以和nii的一样处理，之前发的luna的数据集就是这个格式的

2022-04-06 17:51 UTC, linhandev commented on tools/prepare.py
> +                        dataset_json_dict["training"][osp.basename(f).split(".")[0]]["spacing_resample"] = new_spacing
感觉应该是不会存在4d扫描中不同3d volume spacing不同的情况，头文件里pixdim这个项就是固定7个数，不是针对每个3d volume都有一个pixdim。而且要是3d volume的spacing不同他们应该也没法对应到一个标签上
![image](https://user-images.githubusercontent.com/29757093/162037272-8898e5a0-8b27-4b92-95ee-141ffbd0d3c3.png)

2022-04-06 17:53 UTC, linhandev commented on tools/prepare.py
> +            f_nps = [np.swapaxes(f_np, 0, 2) for f_np in f_nps] # swap to xyz
sitk读取的数据固定是zyx的，只要是sitk读进来都会需要转。我看注释我们最后是存成xyz格式，这样的话这块什么数据集都不应该有问题

2022-04-06 18:33 UTC, linhandev commented on tools/prepare.py
>          else:
我试了一下，基本一样，但是mha和mhd/raw格式sitk读4d的序列有一点区别。至少对于itksnap转存的4d的metaimage是sitk识别不出来他是4d的图像，所以把metaimage的两个后缀mha和mhd单独拿出来了。

在这几个格式上进行了3d和4d的测试
![image](https://user-images.githubusercontent.com/29757093/162044457-7a931386-cf3e-4190-967a-525b9881dfc6.png)

2022-04-08 07:31 UTC, shiyutang approved these changes
prepare line237-238 的缩进需要修改

2022-04-08 07:31 UTC, shiyutang commented on tools/prepare.py
>          else:
如果这样，这里就不需要缩进了

2022-04-08 07:31 UTC, merged