[Feature] Design WrapOp class to process image and label at the same time
PaddleCV-SIG/MedicalSeg pull request #51
Opened 2022-03-29 07:24 UTC by linhandev

初步做了了一个WarpOp类，用一种类似现在wrapper的语法可以实现创建出一个列表的预处理操作，给操作参数。并且可以通过继承重载run方法实现同时访问image和label。

现在只是设计，如果觉得可以这么搞我继续基于这个该prep

2022-03-29 07:30 UTC, linhandev commented
发现要提到nnunet去

2022-03-30 11:49 UTC, shiyutang requested changes
感觉参数处理还是有点复杂，而且没有支持同时传入image和label的op

2022-03-30 11:49 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +        return image, label
需要支持同时传入image 和 label 的op吗

2022-03-30 11:49 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +        print("====")
为什么要传入 args 和 kwargs 呢，不能直接传入需要的参数吗？
感觉后面的逻辑也因为这个参数变得很复杂
op的参数可以通过wrap-partial在外面先传入。

2022-03-30 11:49 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +        print("====")
为什么要传入 args 和 kwargs 呢，不能直接传入需要的参数吗？
感觉后面的逻辑也因为这个参数变得很复杂
op的参数可以通过wrap-partial在外面先传入。

2022-03-30 13:17 UTC, linhandev commented on tools/preprocess_utils/wrap_op.py
> +        return image, label
一些可能会用到，比如crop的操作是要把图像和标签都切到图像中前景的范围。这个范围需要在图像数据中获取到，用在标签上。这种情况就需要图像和标签在一个函数里。

2022-03-30 13:28 UTC, linhandev commented on tools/preprocess_utils/wrap_op.py
> +    class CrossOp(WrapOp):
> 感觉参数处理还是有点复杂，而且没有支持同时传入image和label的op

这个是有支持的，CrossOp是同时用到了图像和标签的示例

2022-03-30 13:35 UTC, linhandev commented on tools/preprocess_utils/wrap_op.py
> +        print("====")
这个如果是图像和数据分开处理warp_partial更简单，但是要支持一起处理的话感觉warp_partial的方案更复杂一些。

一次warp_partial只能得到一个函数，这样如果图像和标签的参数不一样肯定需要wrap两次，像现在的实现一样。两个wrap_partial的参数会有一些是一样的，比如resample的目标大小相同，只是order不一样。

这个args kwargs的处理看起来复杂一点，但其实功能也挺简单，就是把init传进来的参数分给图像和标签，如果参数是tuple就第一个给图像第二个给标签，如果参数不是tuple就图像和标签的参数一样。

感觉这里也可以弃用args，要求所有预处理参数都通过kwargs传。

2022-03-30 14:34 UTC, linhandev commented on tools/preprocess_utils/wrap_op.py
> +        print("====")
加了一个commit去掉了args

2022-03-31 01:45 UTC, shiyutang requested changes
增加了together选择，减少了复杂度

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +        return image, label
需要支持同时传入image 和 label 的op吗

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +    def __init__(self, op, apply="both", **kwargs):
可以把**kwargs 改成**params_dict

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +
可以增加一个together，image和label都传入op做处理

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +            label = self.op(label, **self.label_kwargs)
```
if self.apply is "together":
     image, label = self.op(image, label, self.image_kwags, self.label_kwargs)
else:
        if self.apply in ("both", "image"):
            image = self.op(image, self.image_kwargs)

        if self.apply in ("both", "label"):
            label = self.op(label, self.label_kwargs)
```

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +    class CrossOp(WrapOp):
这个有了together之后感觉可以删除

2022-03-31 01:45 UTC, shiyutang commented on tools/preprocess_utils/wrap_op.py
> +            label = self.op(label, **self.label_kwargs)
可以这样调整，就可以适应所有情况了，不需要对run进行重载，重载的话需要增加类，看上去更加难以理解。

2022-04-01 20:42 UTC, linhandev commented on tools/preprocess_utils/wrap_op.py
> +            label = self.op(label, **self.label_kwargs)
收到，昨天考试，今天就弄一下

2022-08-27 05:37 UTC, closed without merging