For cupy<10.0.0 use numpy in this file
PaddleCV-SIG/MedicalSeg pull request #56
Opened 2022-04-05 06:50 UTC by linhandev

cupy.nan_to_num在10.0.0之前参数不一样，看不太懂应该怎么传。aistudio的cuda版本装不上cupy 10。这样可以在aistudio上用cupy预处理

2022-04-06 03:11 UTC, shiyutang commented
如果不使用CUPY的话，应该使用warning 信息告诉用户。

2022-04-06 03:11 UTC, shiyutang requested changes
如果不使用CUPY的话，应该使用warning 信息告诉用户。

2022-04-06 03:28 UTC, linhandev commented
收到，加一下。

2022-04-06 03:54 UTC, linhandev commented
> 如果不使用CUPY的话，应该使用warning 信息告诉用户。

直接打了一行 [Warning] 貌似import这块的代码会执行两遍，加了一个变量让这行warning只打一次

2022-04-08 07:41 UTC, shiyutang approved these changes
LGTM

2022-04-08 07:44 UTC, merged