feat(unet): add 3d unet
PaddleCV-SIG/MedicalSeg pull request #74
Opened 2022-05-02 18:35 UTC by linhandev

Implement 3d unet

2022-05-05 11:45 UTC, shiyutang requested changes
config/lung_coronavirus/readme.md 中增加在新模型下训练的模型参数、log等

2022-05-05 11:45 UTC, shiyutang commented on configs/lung_coronavirus/lung_coronavirus.yml
> +    # - type: RandomFlip3D
去掉注释部分

2022-05-05 11:45 UTC, shiyutang commented on medicalseg/models/unet.py
> +class UNet(nn.Layer):
这个是否和其他实现对齐呢～ 最好提供对齐效果日志

2022-05-05 11:47 UTC, shiyutang commented on medicalseg/models/unet.py
> +    def __init__(self, in_channels, num_classes, pretrained=None, base_n_kernel=8):
这些参数没有全部体现在配置中。

2022-05-05 11:47 UTC, shiyutang commented on configs/lung_coronavirus/unet_lung_coronavirus_128_128_128_15k.yml
> +  num_classes: 3
参数不对应问题

2022-05-06 23:45 UTC, linhandev commented on configs/lung_coronavirus/unet_lung_coronavirus_128_128_128_15k.yml
> +  num_classes: 3
恩恩，配置文件有点小问题

2022-05-06 23:47 UTC, linhandev commented on medicalseg/models/unet.py
> +class UNet(nn.Layer):
和之前的unet3d实现是对齐的，本身的超参和一些结构在新冠上做了abliation是效果最好的组合。vnet我跑起来有些问题，1w5 iter我这太慢了，在研究vnet这边配置看怎么跑出一个好的效果

2022-05-16 06:37 UTC, shiyutang requested changes
可以在https://github.com/PaddleCV-SIG/MedicalSeg/blob/develop/configs/lung_coronavirus/README.md
和https://github.com/PaddleCV-SIG/MedicalSeg/blob/develop/configs/mri_spine_seg/README.md
 补充unet的效果。

另外，和[这个实现](https://github.com/black0017/MedicalZooPytorch/blob/master/lib/medzoo/Unet3D.py)是对齐的么？可以在相同数据上训练验证下～

2022-05-16 06:42 UTC, shiyutang commented on medicalseg/models/unet.py
> +class UNet(nn.Layer):
和这个实现是对齐的么？
https://github.com/black0017/MedicalZooPytorch/blob/master/lib/medzoo/Unet3D.py
可以在相同数据上训练验证下～

2022-08-27 05:37 UTC, closed without merging