[Feature] update nnunet train
PaddleCV-SIG/MedicalSeg pull request #83
Opened 2022-07-04 03:58 UTC by justld

nnunet 训练
```bash
%cd ~/MedicalSeg/
!python nnunet/train.py --config configs/nnunet/msd_lung_2d_fold_0.yml --use_vdl --do_eval --log_iters 10 --save_interval 1000 --seed 10000 --save_dir output/nnunet_2d/fold_0 --precision fp16
```

2022-07-05 02:35 UTC, shiyutang requested changes
Some details need to be fixed.

2022-07-05 02:35 UTC, shiyutang commented on nnunet/core/val.py
> +            # print('online_eval_foreground_dc:', online_eval_foreground_dc[-1], tp_hard, fp_hard, fn_hard)
注释

2022-07-05 02:35 UTC, shiyutang commented on nnunet/core/val.py
> +from nnunet.datasets import MSDDataset
为什么需要 import MSDdataset

2022-07-05 02:35 UTC, shiyutang commented on nnunet/core/train.py
> +from nnunet.datasets import MSDDataset
同理

2022-07-05 02:35 UTC, shiyutang commented on nnunet/core/train.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
相似代码较多的，文件头增加对nnunet的引用

2022-07-05 02:35 UTC, shiyutang commented on nnunet/core/train.py
> +                    os.makedirs(current_save_dir)
os.makedirs(dir, exist_ok=True)

2022-07-05 02:35 UTC, shiyutang commented on nnunet/train.py
> +    # params of training
comment need to be deleted~

2022-07-05 02:35 UTC, shiyutang commented on nnunet/transforms/augmentation.py
> +    #                                                   seeds=seeds_train, pin_memory=pin_memory)
comment

2022-07-05 02:38 UTC, shiyutang commented on nnunet/train.py
> +
这个文件能否和先有train.py 兼容，通过设置标志判断是否进入nnunet/core/train 还是 core/train

2022-07-05 02:44 UTC, shiyutang commented
先有加入的很多模块是否能增加一些文档，比如MultipleLoss(nn.Layer)， 单独使用时代表什么含义，尽量让这些模块能复用起来。

2022-07-07 06:35 UTC, justld commented
最好不要复用，使用方法和其他方法不一样，比如数据增强的输入和输出是batch的数据[N, C...]，训练时一个batch的label是([N, C, H, W], [N, C, H/2, W/2]...)等。文档等到后面会添加。

2022-07-11 01:59 UTC, shiyutang commented
> 最好不要复用，使用方法和其他方法不一样，比如数据增强的输入和输出是batch的数据[N, C...]，训练时一个batch的label是([N, C, H, W], [N, C, H/2, W/2]...)等。文档等到后面会添加。

嗯嗯，好的，那其他的修改下吧～

2022-07-11 06:15 UTC, justld commented on nnunet/core/val.py
> +            # print('online_eval_foreground_dc:', online_eval_foreground_dc[-1], tp_hard, fp_hard, fn_hard)
已删除

2022-07-11 06:15 UTC, justld commented on nnunet/core/val.py
> +from nnunet.datasets import MSDDataset
已删除

2022-07-11 06:15 UTC, justld commented on nnunet/core/train.py
> +from nnunet.datasets import MSDDataset
已删除

2022-07-11 06:16 UTC, justld commented on nnunet/core/train.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
已添加

2022-07-11 06:16 UTC, justld commented on nnunet/core/train.py
> +                    os.makedirs(current_save_dir)
已修改

2022-07-11 06:16 UTC, justld commented on nnunet/train.py
> +    # params of training
已删除nnunet/train.py

2022-07-11 06:16 UTC, justld commented on nnunet/transforms/augmentation.py
> +    #                                                   seeds=seeds_train, pin_memory=pin_memory)
已删除

2022-07-11 06:17 UTC, justld commented on nnunet/train.py
> +
已修改为标志判断入口，只需要添加参数--nnunet即可转为nnunet训练，具体见代码

2022-07-11 09:07 UTC, shiyutang approved these changes
LGTM

2022-07-11 09:07 UTC, merged